### PR TITLE
Various geocoders

### PR DESCRIPTION
**Pull request by Cyrille37**
@mcguffin Here is the class for geocoders.
I did not finished the JS side... I on the way.

- add file `wp-content/plugins/acf-openstreetmap-field/etc/leaflet-control-geocoders.json`
- and class `wp-content/plugins/acf-openstreetmap-field/include/ACFFieldOpenstreetmap/Core/LeafletGeocoders.php`

You can rework and implements Settings if you want :-)

### CODE REVIEW

**Comment by Cyrille37** [comment]
Done.

@mcguffin  I can let you have time to rework, or reading here changes you want, just tell me :-)

**Comment by Cyrille37** [comment]
_When all will be stable, I will rework to add more specifics options._

**Comment by mcguffin** [comment]
Pardon my impatience with #131 🫣
I'll restain myself to just commentary now.

(1) `etc/leaflet-control-geocoders.json` is really cool. I'm thinking of generic geocoders, not just the ones covered by [perliedman/leaflet-control-geocoder](https://github.com/perliedman/leaflet-control-geocoder). Also with generic settings that detect which geocoder provides what options and needs an API Key or credentials in other formats (e.g. neutrino is asking for a userId). (In the providers json a value like `<insert api-key here>` indicates a placeholder.)
Alone the class constants and the explicit name in geocoderFactory.js would break the concept.  
Just let me know, how far you would like to bring this.

(2) I would rename `LeafletGeocoders` to just `Geocoders`. I'm thinking about supporting more map engines than just leaflet. Like MapBox, [cesium](https://cesium.com/platform/cesiumjs/), OpenLayers, ... still songs from a distant future.

(3) I think we should get rid of the whole `htmlTemplate` thing and retreive the label text from `geocoderResult.name`.

**Comment by Cyrille37** [comment]
Many cool ideas  :tada: 

By the way, I think to walk step by step to save dev time AND user experience. WP plugin are for users, like a dev can write plugin for his custom needs :wink:   [KISS](https://en.wikipedia.org/wiki/KISS_principle)

(2) For this time I prefer to keep the goal on `leaflet-control-geocoder`. On another sprint we will implement other providers. Another objective can be to use and contribute to others projects and assembling them together like `acf-openstreetmap-field + leaflet-control-geocoder`. So we can contribute or create compatible geocoders with `leaflet-control-geocoder`.

(3) But `htmlTemplate` is really usefull for formatting the result string. I've created issues https://github.com/perliedman/leaflet-control-geocoder/issues/357 and https://github.com/perliedman/leaflet-control-geocoder/issues/358 to talk for a harmonisation of geocoders `Interface`.

(4) I will add, because I need it, option to LeafletGeocoders to permit to use `leaflet-control-geocoder` extension, aka geocoders that are not provided with the plugin. Option will declare JS & CSS to load.

Thanks a lot for this discussion :love_letter: 

Regards & cheers

**Comment by Cyrille37** [comment]
Also, can you merge this one because #131 was not completed :-)

**Comment by Cyrille37** [comment]
Hi @mcguffin 
Thanks for the merge :-)

What can we plan?
- do want to work on the geocoders settings ? Or I've to do it ?
- I'm thinking to refine individual geocoder options those days.

**Comment by Cyrille37** [comment]
## About settings

May I add optional validation data in geocoders options description in `wp-content/plugins/acf-openstreetmap-field/etc/leaflet-control-geocoders.json` ?

if the option value is null, then the value is not transmitted to the geocoder, which will use its default value.

As validation would be optional, we could describe it in these two ways, for example the `apiKey` :

```json
"apiKey": null,
```

```json
"apiKey": {
 "required": true
}
```

I think about that for option like Photon `nameProperties` which is an array of values (_`nameProperties: ['name', 'street', 'suburb', 'hamlet', 'town', 'city', 'state', 'country']`_).

And for those Settings & Validation stuff I usually use the simple but effective [jeremyHixon/RationalOptionPages](https://github.com/jeremyHixon/RationalOptionPages) :wink:

**Comment by Cyrille37** [comment]
Forget about the proposed validation stuff, **it's too ambitious**, that's for another sprint :-)

**Comment by mcguffin** [comment]
Just finished some minor refactoring and cleanup.

My plan for today is to add the testing map to the settings page and to generate the Geocoder specific settings from the geocoder json.  

Relevant changes so far:
 - geocoder names are now lowercase. In addition there is a label that can be presented to the user.
 - `apiKey` in the json now is now `"<Servicename API Key>"`. The `^<.*>$` indicates a crendential input for the settings page. `Servicename API Key` will be the field label. Allows multipart credentials like Neutrino‘s userID.
 - `$option[$geocoder_engine]` is just merged with the default options from the geocoder and passed to the js.

**Comment by Cyrille37** [comment]
Ok I'll merge in my branch [various_geocoders](https://github.com/Cyrille37/acf-openstreetmap-field/tree/various_geocoders).

_It's not easy to work together on same parts of code :-( I've to erase my changes._

**Comment by mcguffin** [comment]
Uuh, my apologies. It wasn't on purpose. 
I'll restrict myself to the settings today.

**Comment by Cyrille37** [comment]
> 'll restrict myself to the settings today.

No. I'll stop for now, I'm waiting for you to finish your ideas :-)

**Comment by Cyrille37** [comment]
Keep me informed, I'll do some tests when you've finished.

**Comment by mcguffin** [comment]
@Cyrille37 Lets move our conversation to the issue #71.

**Pull request merged**
